version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
